server:
  port: 4060
 
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: frame
    password: test
    url: jdbc: jdbc:oracle:thin:@222.212.141.40:9106:VASTEST
  elasticjob:
    zookeeper:
      server-lists: 127.0.0.1:2181
      namespace: vasms-daemon
