server:
  port: 5003

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: frame
    password: test
    url: jdbc:oracle:thin:@222.212.141.40:9106:VASTEST

zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      password: vas
      username: vas
      queue: zipkin
  storage:
    type: mysql
